### ISSUE TITLE
Adding a way to run student-written tests while cloning

### ISSUE THREAD

**Issue by amaberg** [repobee/repobee-junit4#53]
It would be nice to able to run the student-generated tests in every repo using repobee

**Comment by slarse** [comment]
@amaberg Thanks for the suggestion, I think this should be fairly easy to implement.

**Comment by slarse** [comment]
Basic idea:

Add a new CLI option `--junit4-run-student-tests`, that runs test classes from the student's own repo. Probably the easiest way to accomplish this is  to still require the reference tests directory, and still look for the test classes there, but after that initial lookup go look for equivalent test classes in the student's repo.
