### ISSUE TITLE
Inconsistent use of argument names: --reference-tests-dir vs --junit4-reference-tests-dir 

### ISSUE THREAD

**Issue by Quincunxial** [repobee/repobee-junit4#96]
When using the `generate-rtd` command, the path to the reference test directory can be set with the `--reference-tests-dir`argument. However, when hooking the plugin to the `repos clone` command, the RTD is set with the `--junit4-reference-tests-dir `. This means that the `generate-rtd` command can´t make use of the stored RTD path as set with the `config wizard`.  It would be nice to have consistent terminology and to be able to use the same config setting for both commands.

**Comment by slarse** [comment]
Thanks for the constructive suggestion!

This would definitely be desirable. As it happens, I just fixed a bug reported by another user that will make it possible for both arguments to have the same name (repobee/repobee#757). I'll make sure this makes it into the next release.
