### ISSUE TITLE
Instructions for junit4 RTD

### ISSUE THREAD

**Issue by amaberg** [repobee/repobee-junit4#97]
The command given in the instructions for junit4 generate-rtd does not work (because junit4 needs to be written twice and not once as in the instructions). It also specifies students, which doesn't make sense here.

**Comment by slarse** [comment]
@amaberg That's a typo, thanks!

As per our discussion, there's also no mention of the `--to|--template-org-name` argument, which a teaching assistant probably doesn't know about.

**Comment by slarse** [comment]
Docs updated, thanks for your contribution!
